package com.bawei.dianshangjinmonth02.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bawei.dianshangjinmonth02.bean.SaveInfoBean;

import com.bawei.dianshangjinmonth02.dao.SaveInfoBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig saveInfoBeanDaoConfig;

    private final SaveInfoBeanDao saveInfoBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        saveInfoBeanDaoConfig = daoConfigMap.get(SaveInfoBeanDao.class).clone();
        saveInfoBeanDaoConfig.initIdentityScope(type);

        saveInfoBeanDao = new SaveInfoBeanDao(saveInfoBeanDaoConfig, this);

        registerDao(SaveInfoBean.class, saveInfoBeanDao);
    }
    
    public void clear() {
        saveInfoBeanDaoConfig.clearIdentityScope();
    }

    public SaveInfoBeanDao getSaveInfoBeanDao() {
        return saveInfoBeanDao;
    }

}
